name: Unity CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.7f1'  # Replace with your Unity version
          targetPlatform: 'StandaloneLinux64'  # Specify the target platform

      - name: Cache Unity packages
        uses: actions/cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/PackagesLock.json') }}

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.7f1'  # Replace with your Unity version
          targetPlatform: 'StandaloneLinux64'  # Specify the target platform
          buildName: 'StandaloneLinux64'
          buildPath: build

      - name: Set build artifact path
        run: echo "BUILD_PATH=build/StandaloneLinux64" >> $GITHUB_ENV

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.BUILD_PATH }}
