name: Unity CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Use ubuntu-latest for Linux environment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Install Unity
        run: |
          curl -sS https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.yml | grep downloadUrl | head -n 1 | cut -d ' ' -f 4 | xargs wget -O unity-editor.AppImage
          chmod +x unity-editor.AppImage
          ./unity-editor.AppImage --install-location ./UnityHub --unattended --package Unity --package Linux-Android --package Windows-Mono --package Web-GL
          
      - name: Cache Unity packages
        uses: actions/cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/PackagesLock.json') }}
          
      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results.xml
          
      - name: Build project
        run: |
          mkdir -p build
          ./UnityHub/Editor/2022.3.7f1/Unity/Editor/Unity -quit -batchmode -nographics -projectPath . -buildTarget StandaloneLinux64 -buildPath build/StandaloneLinux64
        continue-on-error: true
        
      - name: Set build artifact path
        run: echo "BUILD_PATH=build/StandaloneLinux64" >> $GITHUB_ENV
        
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.BUILD_PATH }}
