name: Unity CI

on: [push, pull_request]

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Unity
        uses: game-ci/setup-unity@v1
        with:
          unityVersion: '2022.3.7f1'  # Replace with your Unity version
          components: 'unity, android'  # Replace with necessary components
          license: ${{ secrets.UNITY_LICENSE }}
      - name: Cache Unity packages
        uses: actions/cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/PackagesLock.json') }}
      - name: Run Unity tests
        run: |
          unity -batchmode -runTests -projectPath . -testPlatform playmode
          unity -batchmode -runTests -projectPath . -testPlatform editmode
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: TestResults
